version: '3.8'
services:
  web:
    build: .
    container_name: Brain-Battles
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
    volumes:
      - ./instance:/app/instance  # Persist the SQLite database in the 'instance' directory
